### ISSUE TITLE
segfault on wrong HUE_USERNAME

### ISSUE THREAD

**Issue by relet** [Celerway/labrador#1]
```
{"time":"2024-06-04T21:28:01.93237962+02:00","level":"INFO","msg":"MQTT Broker announced on mDNS.","service name":"labrador","service type":"_mqtt._tcp","port":1883,"local IPs":["10.0.0.6","172.17.0.1"]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71980d]

goroutine 19 [running]:
github.com/celerway/labrador/gohue.(*HueClient).Load(0xc00011f080, {0x8b7c80?, 0xb7b180?})
	/home/celerway/labrador/gohue/controller.go:102 +0xad
github.com/celerway/labrador/broker.(*State).Run(0xc0001260c0, {0x8b7bd8, 0xc000134230})
	/home/celerway/labrador/broker/init.go:82 +0x50e
main.run.func1()
	/home/celerway/labrador/main.go:42 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/root/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

**Comment by relet** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71980d]

goroutine 19 [running]:
github.com/celerway/labrador/gohue.(*HueClient).Load(0xc000244750, {0x8b7c80?, 0xb7b180?})
	/home/celerway/labrador/gohue/controller.go:102 +0xad
github.com/celerway/labrador/broker.(*State).Run(0xc0001260c0, {0x8b7bd8, 0xc000134230})
	/home/celerway/labrador/broker/init.go:82 +0x50e
main.run.func1()
	/home/celerway/labrador/main.go:42 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/root/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```
